server:
  port: 8888
spring:
  application:
    name: config-server 
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jeanlucasbs/microservices/tree/main/code-config-server
          default-label: main
          search-paths:
          - 'greeting-service*'